//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemporaryListener
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessCard
    {
        public int Id { get; set; }
        public int CardType { get; set; }
        public bool SignedIn { get; set; }
        public string CardId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
